services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pixorama
      POSTGRES_PASSWORD: "NegepvbTZGpAlYZjpfbJtjq-EVsYPjK3"
    volumes:
      - pixorama_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "QoljLZKNNP4eOtypPDrRNtqGgvn8noq8"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pixorama_test
      POSTGRES_PASSWORD: "G2yvr1DRcUcufTL9X14_WuQt0v7_Omn6"
    volumes:
      - pixorama_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "hMFr-jsfu58I54nrfE4e6OuOUwJW1aci"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  pixorama_data:
  pixorama_test_data:
