services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe
      POSTGRES_PASSWORD: "vKy1Q6ToXabMjmr0wRoyp8i5h08ItHqK"
    volumes:
      - magic_recipe_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "w3EOgN3G3vp9yg6EYw3AJz7Jg9BT3tgw"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe_test
      POSTGRES_PASSWORD: "WnMfYRBeYgFCHlrYwG8WHE3HPfwMSQyx"
    volumes:
      - magic_recipe_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "pg91_E7W8yHPYv3IRK0RInnvURTfi-s9"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  magic_recipe_data:
  magic_recipe_test_data:
